CREATE TABLE CLIENTES (
    CLI_ID INTEGER NOT NULL,
    CLI_NOME VARCHAR(30) NOT NULL,
    CLI_SALDO DECIMAL(9,0) NOT NULL,
    DT_ATUALIZACAO DATE,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE TRANSACOES (
    TRX_ID INTEGER NOT NULL,
    CLI_ID INTEGER NOT NULL,
    TRX_TIPO CHAR(1) NOT NULL,
    TRX_VALOR DECIMAL(9,0) NOT NULL,
    DT_PROCESSAMENTO DATE,
    PRIMARY KEY (TRX_ID)
);

CREATE TABLE ERROS_PROCESSAMENTO (
    ID_ERRO INTEGER GENERATED ALWAYS AS IDENTITY,
    CLI_ID INTEGER,
    DESCRICAO_ERRO VARCHAR(100),
    DT_OCORRENCIA TIMESTAMP
);

CREATE TABLE HISTORICO_TRANSACOES (
    HIST_ID INTEGER GENERATED ALWAYS AS IDENTITY,
    TRX_ID INTEGER NOT NULL,
    CLI_ID INTEGER NOT NULL,
    TRX_TIPO CHAR(1) NOT NULL,
    TRX_VALOR DECIMAL(9,0) NOT NULL,
    SALDO_ANTERIOR DECIMAL(9,0),
    SALDO_NOVO DECIMAL(9,0),
    STATUS_PROCESSAMENTO VARCHAR(30),
    DESCRICAO VARCHAR(100),
    DT_HISTORICO TIMESTAMP
);

CREATE INDEX IDX_TRANSACOES_CLI_ID
ON TRANSACOES (CLI_ID);

CREATE INDEX IDX_ERROS_CLI_ID
ON ERROS_PROCESSAMENTO (CLI_ID);

CREATE INDEX IDX_HISTORICO_CLI_ID
ON HISTORICO_TRANSACOES (CLI_ID);

CREATE INDEX IDX_HISTORICO_TRX_ID
ON HISTORICO_TRANSACOES (TRX_ID);