SELECT CLI_NOME, CLI_SALDO
FROM CLIENTES
WHERE CLI_ID = ?;

INSERT INTO CLIENTES
(CLI_ID, CLI_NOME, CLI_SALDO, DT_ATUALIZACAO)
VALUES
(?, ?, ?, CURRENT DATE);

UPDATE CLIENTES
SET CLI_NOME = ?, CLI_SALDO = ?, DT_ATUALIZACAO = CURRENT DATE
WHERE CLI_ID = ?;

UPDATE CLIENTES
SET CLI_SALDO = ?, DT_ATUALIZACAO = CURRENT DATE
WHERE CLI_ID = ?;

INSERT INTO TRANSACOES
(TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES
(?, ?, ?, ?, CURRENT DATE);

INSERT INTO ERROS_PROCESSAMENTO
(CLI_ID, DESCRICAO_ERRO, DT_OCORRENCIA)
VALUES
(?, ?, CURRENT TIMESTAMP);

INSERT INTO HISTORICO_TRANSACOES
(TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, SALDO_ANTERIOR, SALDO_NOVO,
 STATUS_PROCESSAMENTO, DESCRICAO, DT_HISTORICO)
VALUES
(?, ?, ?, ?, ?, ?, ?, ?, CURRENT TIMESTAMP);

DECLARE CURSOR_RELATORIO CURSOR FOR
SELECT CLI_ID, CLI_NOME, CLI_SALDO
FROM CLIENTES
ORDER BY CLI_ID;

COMMIT;

ROLLBACK;